apiVersion: v1
kind: Secret
metadata:
  name: database-secret-config
type: Opaque
data:
  MONGO_DB_CONNECTION_STRING : base64 value

//base64 generation:
//(values of echo "mongodb+srv://username:password@xyz.mongodb.net/torque?retryWrites=true&w=majority" | base64)
//Something like this: cnY6Ly9hZG1pbjpzdW1pbWluaXZpamF5QHRvcnF1ZS5ua2xnbS5tb25nb2RiLm5ldC90b3JxdWU/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yCg==
