apiVersion: v1
kind: Service
metadata:
  name: torquelogger
  labels:
    app: torquelogger
    service: torquelogger
spec:
  ports:
  - port: 4000
    name: http
  selector:
    app: torquelogger
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: torquelogger
  labels:
    account: torquelogger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torquelogger-v1
  labels:
    app: torquelogger
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torquelogger
      version: v1
  template:
    metadata:
      labels:
        app: torquelogger
        version: v1
    spec:
      serviceAccountName: torquelogger
      containers:
      - name: torquelogger
        image: deepakdpk6/torquelogger:latest
        imagePullPolicy: IfNotPresent
        envFrom:
              - secretRef:
                  name: database-secret-config
        ports:
        - containerPort: 4000
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
